version: '3'
services:
  clasp-app:
    container_name: clasp-app
    build:
      context: app
    tty: true
    environment:
      - TZ=Asia/Tokyo
    ports:
      - "37473:37473"
    volumes:
      - ./src:/work
      - clasp-home:/root
      - ./app/clasp-login.sh:/clasp-login.sh:ro

volumes:
  clasp-home:

